<%@ page import="com.ecosmosis.orca.msgcode.*"%>
<%@page import="com.ecosmosis.orca.member.printings.MemberIdBean"%>
<%@page import="com.ecosmosis.orca.member.printings.MemberPrintManager"%>
<%@page import="com.ecosmosis.orca.stockist.StockistManager"%>
<html>
<head>
<title></title>

<%@ include file="/lib/header.jsp"%>
<%
	String editURL = "";//Sys.getControllerURL(MemberManager.TASKID_BASIC_EDIT_MEMBER, request);

	MvcReturnBean returnBean = (MvcReturnBean) request.getAttribute(MvcReturnBean.RETURNBEANCODE);

	MemberIdBean[] beans = (MemberIdBean[]) returnBean.getReturnObject(MemberPrintManager.RETURN_LIST_CODE);

	Map records = (Map) returnBean.getReturnObject(StockistManager.RETURN_SHOWRECS_CODE);
	
	Map status = (Map) returnBean.getReturnObject(MemberPrintManager.RETURN_IDSTATUS_CODE);
        
	Map register = (Map) returnBean.getReturnObject(MemberPrintManager.RETURN_REGISTER_CODE);        
	
	boolean canView = (beans != null);
	
	boolean showResult = (beans != null && beans.length>0);
%>

	<script language="javascript"> 	 
	</script>
</head>

<body>

<div class="functionhead">Database Updated </div>

<hr>

<br>

<%@ include file="/lib/return_error_msg.jsp"%>

<c:if test="<%= showResult %>">
	<input class="noprint" type="button" value="Print" onClick="window.print();">
	<br>
	<br>	
</c:if>
	

<c:if test="<%= canView %>">
<table class="listbox" width="40%">
	
	<tr class="boxhead" valign=top>
		<td width="5%"><i18n:label localeRef="mylocale" code="<%=StandardMessageTag.NO%>" /></td>
		<td>CFO Number</td>								
		<td>Pin</td>
		<td  width="8%">Generated By</td>
		<td width="20%">Generated Date</td>
                <td width="30%">Register Type</td>
                <td width="20%">Buyer Code</td>
		<td align=center width="10%">Status</td>
	</tr>
<c:choose>
<c:when test="<%= showResult %>">

	<%
		String rowCss = "";
		for (int i = 0; i < beans.length; i++) {
			
			if (i % 2 == 0)
				rowCss = "even";
			else
				rowCss = "odd";
	%>
	
	<tr class="<%= rowCss %>" valign=top>
		<td width="5%" align=right><%= (i+1) %>.</td>
		<td nowrap><%= beans[i].getId() %></td>
		<td align=center nowrap><%= beans[i].getEpin() %></td>
		<td align=left><%= beans[i].getStd_createBy() %></td>		
		<td align=center nowrap><%= beans[i].getStd_createDate() %> <%= beans[i].getStd_createTime() %></td>
		<td align=center nowrap><%= MemberPrintManager.defineRegisterType(beans[i].getReferenceNo())%></td>                
                <%if(beans[i].getBuyerCode() != null){%>
                   <td align=center nowrap><%= beans[i].getBuyerCode()%></td>
                <%}else{ %>   
                   <td align=center nowrap>-</td>       
                <%}%>
		<td nowrap>
		<%if(beans[i].getStatus() == MemberPrintManager.STATUS_UNUSED){%>
		  	<font color="blue"><%= (MemberPrintManager.defineIDStatus(MemberPrintManager.STATUS_UNUSED)) %></font>
		<%}else{ %>
		  	<font color="red"><%= (MemberPrintManager.defineIDStatus(MemberPrintManager.STATUS_USED)) %></font>
		<%}%>
		</td>
	</tr>
	<%
		}//end for
	%>	

</c:when>	
<c:otherwise>
	<tr>
		<td colspan=9 align="center"><b>No records found.</b></td>	  
	</tr>

</c:otherwise>
</c:choose>
</table>

	<c:if test="<%= showResult %>">
		
		<br>
		<br>
		<input class="noprint" type="button" value="Print" onClick="window.print();">
	</c:if>
	
</c:if>



</body>
</html>
