<%@ page import="com.ecosmosis.orca.msgcode.*"%>
<%@page import="com.ecosmosis.orca.member.lucky.MemberLuckyBean"%>
<%@page import="com.ecosmosis.orca.member.lucky.MemberLuckyManager"%>
<%@page import="com.ecosmosis.orca.stockist.StockistManager"%>
<html>
<head>
<title></title>

<%@ include file="/lib/header.jsp"%>
<%
	String editURL = "";//Sys.getControllerURL(MemberManager.TASKID_BASIC_EDIT_MEMBER, request);

	MvcReturnBean returnBean = (MvcReturnBean) request.getAttribute(MvcReturnBean.RETURNBEANCODE);

	MemberLuckyBean[] beans = (MemberLuckyBean[]) returnBean.getReturnObject(MemberLuckyManager.RETURN_LIST_CODE);

	Map status = (Map) returnBean.getReturnObject(MemberLuckyManager.RETURN_IDSTATUS_CODE);
        
        Map records = (Map) returnBean.getReturnObject(StockistManager.RETURN_SHOWRECS_CODE);
		
	boolean canView = (beans != null);
	
	boolean showResult = (beans != null && beans.length>0);
%>

	<script language="javascript"> 	 
	</script>
</head>

<body>

<div class="functionhead">Search Generated Lucky Numbers</div>

<form name="frmSearch" method="post" action="<%=Sys.getControllerURL(MemberLuckyManager.TASKID_STARTER_LIST, request)%>" >
<table border="0" class="noprint">
        <tr>
            <td class="td1">CFO No.:</td>
            <td><std:memberid name="MemberID" form="frmSearch"/></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
	<tr>
		<td class="td1">Generated Date From:</td>
		<td><std:input type="date" name="DateFrom" value="now"/></td>
		<td>&nbsp;</td>
		<td class="td1">Generated Date To:</td>
		<td><std:input type="date" name="DateTo" value="now"/></td>
	</tr>        
        <tr>
                <td class="td1">Status:</td>
                <td><std:input type="select" name="Status" options="<%=status %>" /></td>
		<td>&nbsp;</td>
		<td class="td1">Display:</td>
		<td><std:input type="select" name="Limits" options="<%=records %>" /></td>
	</tr>

</table>

<br>
<input class="noprint" type="submit" value="Submit">
</form>

<hr>

<br>


<%@ include file="/lib/return_error_msg.jsp"%>

<c:if test="<%= showResult %>">
	<input class="noprint" type="button" value="Print" onClick="window.print();">
	<br>
	<br>	
</c:if>
	

<c:if test="<%= canView %>">
<table class="listbox" width="40%">
	
	<tr class="boxhead" valign=top>
		<td width="5%"><i18n:label localeRef="mylocale" code="<%=StandardMessageTag.NO%>" /></td>
                <td width="20%">Cash Bill</td>
                <td width="20%">NoID </td>
                <td width="30%">Name </td>
		<td>Lucky Number</td>								
		<td>Status</td>								
                <td  width="8%">Generated By</td>
		<td width="20%">Generated Date</td>                
	</tr>
<c:choose>
<c:when test="<%= showResult %>">

	<%
		String rowCss = "";
                for (int i = 0; i < beans.length; i++) {
			
			if (i % 2 == 0)
				rowCss = "even";
			else
				rowCss = "odd";
        %>
	
	<tr class="<%= rowCss %>" valign=top>
		<td width="5%" align=right><%= (i+1) %>.</td>
                <td align=center nowrap><%= beans[i].getCounterId()%></td>
                <%if(beans[i].getBuyerCode() != null){%>
                   <td align=center nowrap><%= beans[i].getBuyerCode()%></td>
                <%}else{ %>   
                   <td align=center nowrap>-</td>       
                <%}%>
                <td align=left nowrap><%= beans[i].getBuyerName()%></td>
                <td nowrap><%= beans[i].getId() %></td>
		<td nowrap>
		<%if(beans[i].getStatus() == MemberLuckyManager.STATUS_VOIDED){%>
		  	<font color="red"><%= (MemberLuckyManager.defineIDStatus(MemberLuckyManager.STATUS_VOIDED)) %></font>
		<%}else{ %>
		  	<font color="blue"><%= (MemberLuckyManager.defineIDStatus(MemberLuckyManager.STATUS_ACTIVE)) %></font>
		<%}%>
		</td>                
                
		<td align=left><%= beans[i].getStd_createBy() %></td>	                
		<td align=center nowrap><%= beans[i].getStd_createDate() %> <%= beans[i].getStd_createTime() %></td>

            </tr>
	<%
		}//end for
	%>	

</c:when>	
<c:otherwise>
	<tr>
		<td colspan=9 align="center"><b>No records found.</b></td>	  
	</tr>

</c:otherwise>
</c:choose>
</table>

	<c:if test="<%= showResult %>">
		
		<br>
		<br>
		<input class="noprint" type="button" value="Print" onClick="window.print();">
	</c:if>
	
</c:if>



</body>
</html>
